image: alpine:latest

stages:
  - deploy
  
pages:
  stage: deploy
  script:
  - echo "******************************************"
  - ls
  - mkdir public
  - cp ./*.html public
  - cp -r ./assets public
  artifacts:
    paths:
    - public
    expire_in: 1h
  only:
  - main